x-env: &env
  environment:
    - DB_NAME=${DB_NAME}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT-5432}

version: "3.5"
services:
  db:
    container_name: kdrama_db
    restart: always
    image: 'postgres:14.5'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    depends_on:
      - pgadmin
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: kdrama_pgadmin
    restart: always
    image: dpage/pgadmin4:6.7
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin/data